import type { Metadata } from "next";
import { Inter } from "next/font/google";

/** Global styles for the whole app */
import "./globals.css";

/** Mantine impelementation */
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

/** Navigation for the app */

const inter = Inter({ subsets: ["latin"] });

/** global metadata, will be overriden in pages */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Let's roll function
 * @param param0 
 * @returns 
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
