export enum MantineInputType {
  Checkbox = "Checkbox",
  //  Chip = "Chip",
  ColorInput = "ColorInput",
  ColorPicker = "ColorPicker",
  //  Fieldset = "Fieldset",
  //  FileInput = "FileInput",
  Input = "Input",
  JsonInput = "JsonInput",
  //  NativeSelect = "NativeSelect",
  // NumberInput = "NumberInput",
  //  PasswordInput = "PasswordInput",
  //  PinInput = "PinInput",
  //  Radio = "Radio",
  //  Rating = "Rating",
  //  SegmentedControl = "SegmentedControl",
  Slider = "Slider",
  Switch = "Switch",
  //  Textarea = "Textarea",
  //  TextInput = "TextInput",
  TagsInput = "TagsInput",
}
